use crate::models::field::Field;

#[derive(Clone)]
pub struct Cell {
    // TODO: いくつかの ANCI escape code の列挙を設定する。
    pub background: String,
    pub foreground: String,
    pub symbol: char,
    pub x: u8,
    pub y: u8,
}

pub struct Screen {
    pub matrix: [[Cell; 80]; 24],
}

impl Screen {
    pub fn new() -> Screen {
        let default_cell = Cell {
            x: 0,
            y: 0,
            symbol: ' ',
            background: String::from(""),
            foreground: String::from(""),
        };
        let mut screen = Screen {
            // TODO: 短くする。おそらくマクロでどうにかする気はする。または ndarray などのライブラリで解決する。
            matrix: [
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
            ],
        };

        // Assign the initial data.
        //let max_row_index = (screen.matrix.len() - 1) as u8;
        // TODO: as u8 をこの row_index へ実行したい。下記 column_index も同様。
        for row_index in 0..screen.matrix.len() {
            let row = &screen.matrix[row_index];
            //let max_column_index = (row.len() - 1) as u8;
            for column_index in 0..row.len() {
                // TODO: let cell = screen.matrix[row_index][column_index]; みたいに一旦変数に落として更新したい。
                screen.matrix[row_index][column_index].x = column_index as u8;
                screen.matrix[row_index][column_index].y = row_index as u8;
            }
        }
        screen
    }
    // TODO: models を直接参照しない。間に React の Props みたいな更新クエリの概念を挟む。
    pub fn update(&mut self, field: &Field) {
        for (y, row_of_field_element) in field.matrix.iter().enumerate() {
            for (x, field_element) in row_of_field_element.iter().enumerate() {
                // TODO: FieldElement の位置と Screen の位置が同じになるとは限らない。というか、普通は Field の方が Screen の Field 描画範囲より大きい。
                self.matrix[y][x].symbol = field_element.get_display();
            }
        }
    }
}
