pub struct MapElementUpdate {
    pub background: String,
    pub foreground: String,
    pub symbol: char,
}

pub struct ScreenUpdate {
    // A map showing the area around the hero.
    pub map: Vec<Vec<MapElementUpdate>>,
}

#[derive(Clone)]
pub struct Cell {
    // TODO: いくつかの ANCI escape code の列挙を設定する。
    pub background: String,
    pub foreground: String,
    pub symbol: char,
    pub x: u8,
    pub y: u8,
}

pub struct Screen {
    pub matrix: [[Cell; 80]; 24],
}

impl Screen {
    pub fn new() -> Screen {
        let default_cell = Cell {
            x: 0,
            y: 0,
            symbol: ' ',
            background: String::from(""),
            foreground: String::from(""),
        };
        let mut screen = Screen {
            // TODO: 短くする。おそらくマクロでどうにかする気はする。または ndarray などのライブラリで解決する。
            matrix: [
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
                [
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                    default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(), default_cell.clone(),
                ],
            ],
        };

        // Assign the initial data.
        //let max_row_index = (screen.matrix.len() - 1) as u8;
        // TODO: as u8 をこの row_index へ実行したい。下記 column_index も同様。
        for row_index in 0..screen.matrix.len() {
            let row = &screen.matrix[row_index];
            //let max_column_index = (row.len() - 1) as u8;
            for column_index in 0..row.len() {
                // TODO: let cell = screen.matrix[row_index][column_index]; みたいに一旦変数に落として更新したい。
                screen.matrix[row_index][column_index].x = column_index as u8;
                screen.matrix[row_index][column_index].y = row_index as u8;
            }
        }
        screen
    }
    pub fn update(&mut self, screen_update: &ScreenUpdate) {
        // Map
        let map_xy = (2, 2);
        for (map_y, map_row) in screen_update.map.iter().enumerate() {
            for (map_x, map_element) in map_row.iter().enumerate() {
                let xy = (map_xy.0 + map_x, map_xy.1 + map_y);
                self.matrix[xy.1][xy.0].symbol = map_element.symbol;
            }
        }
    }
    pub fn create_output_as_lines(&self) -> Vec::<String> {
        self.matrix.iter()
            .map(|row| {
                row.iter()
                    .map(|cell| cell.symbol.to_string())
                    .collect::<Vec<String>>()
                    .join("")
            })
            .collect::<Vec<String>>()
    }
}
