name: Run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.53.0'
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
