on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      # The following settings are copied from https://github.com/actions/cache/blob/main/examples.md#rust---cargo .
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.68.0'
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
